# Generated by Django 3.1.5 on 2021-01-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
