# Generated by Django 3.1.5 on 2021-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20210120_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetofficers',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
    ]
